version: "3"
services:
  nginx:
    image: dmitriy228/docker_nginx_jenkins:latest
    ports: 
      - "80:80"
    restart: always
    networks:
      - mynetwork    
  apache_php:
    image: dmitriy228/docker_apache_jenkins:latest
    container_name: apache_php
    ports:
      - "8090:80"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
